// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAiT9REBms9TBoz7aPKbh47Io56lOhMfM',
    appId: '1:880220125401:android:49a2f7e69002598351e6c8',
    messagingSenderId: '880220125401',
    projectId: 'chatgame-f0cf3',
    storageBucket: 'chatgame-f0cf3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaMsxC1yhDDDUHJgBDHVSy8-LOw4yv_W0',
    appId: '1:880220125401:ios:ac4ea0b863b167fd51e6c8',
    messagingSenderId: '880220125401',
    projectId: 'chatgame-f0cf3',
    storageBucket: 'chatgame-f0cf3.appspot.com',
    iosBundleId: 'com.example.chatGame',
  );
}
